### ISSUE TITLE
Accept integer resource values for text size parameters

### ISSUE THREAD

**Issue by starkej2** [wooplr/Spotlight#23]
Methods such as `setHeadingTvSize()` should have an override that accepts a dimen resource parameter to supplement the existing methods that accept float/pixel values.

**Comment by starkej2** [comment]
Nevermind, this is already possible

**Comment by starkej2** [comment]
Actually, there needs to be a method similar to this to be able to pass in dimen values.
https://developer.android.com/reference/android/widget/TextView.html#setTextSize(int, float)

**Comment by dhavalwooplr** [comment]
Added a method which will accept dimension unit and size in integer. 
`setHeadingTvSize(int dimenUnit, int Size)`
