### ISSUE TITLE
Using it with Rectangular Widgets like EditText, TextView?

### ISSUE THREAD

**Issue by haideralipunjabi** [wooplr/Spotlight#29]
I am not able to use it properly with widgets having a Rectangular shape like TextView, EditText, etc.

Is it possible you can add rectangle shape as well?

**Comment by hardikamal** [comment]
@haideralipunjabi Any solution found to this?

**Comment by haideralipunjabi** [comment]
@hardikamal Nope, I just used a rectangular colored box, with dark overlay to use with Rectangular Views

**Comment by hardikamal** [comment]
@haideralipunjabi can you share the implementation...did you use your implementation with spotlight?

**Comment by haideralipunjabi** [comment]
@hardikamal I used [Android-Cling](https://github.com/MajeurAndroid/Android-Cling), and made this method

`  public void showSimpleHelp(View v,String Title, String Content)
   {


    ClingManager mClingManager = new ClingManager(this);


       mClingManager.addCling(new Cling.Builder(this)
               .setTitle(Title)
               .setContent(Content)
               .setTarget(new ViewTarget(this,v.getId()))
               .setMessageBackground(Color.parseColor("#4fbe89"))
               .setClingColor(Color.parseColor("#dd000000"))
               .build());



       mClingManager.setCallbacks(new ClingManager.Callbacks() {
           @Override
           public boolean onClingClick(int position) {
               // We return false to tell to cling manager that we didn't handle this,
               // so it can perform the default action (ie. showing the next Cling).
               // This is the default value returned by super.onClingClick(position), so
               // in a real project, we would just leave this method unoverriden.
               return false;
           }

           @Override
           public void onClingShow(int position) {
           }

           @Override
           public void onClingHide(int position) {


           }
       });

       mClingManager.start();



   }
`
