### ISSUE TITLE
Certain lines (the half circle around target) not shown

### ISSUE THREAD

**Issue by InI4** [wooplr/Spotlight#30]
I have now clue. It was all painting fine during development. Now I pushed a release version to Play Store and some animations do not seem to run properly. Anyone having experienced the same?

**Comment by 29jitender** [comment]
Please use following pro-guard rules.

-keep class com.wooplr.spotlight.** { *; }
-keep interface com.wooplr.spotlight.**
-keep enum com.wooplr.spotlight.**

**Comment by InI4** [comment]
Actually I did, though I wonder what this can help. I didn't see Reflection
being used.

Am 26.09.2016 09:56 schrieb "Jitender Chaudhary" <notifications@github.com>:

**Comment by InI4** [comment]
Just to remark. This is a close without a solution. The pro-guard rules do not change anything of the mentioned behaviour.
