### ISSUE TITLE
Any way to display it on recyclerview item

### ISSUE THREAD

**Issue by hardikamal** [wooplr/Spotlight#34]
Hi @ankitsabharwal Thanks for the awesome library.

Is there any way to show it in the recyclerview item??

**Comment by dhavalwooplr** [comment]
@hardikamal To show a spotlight in the recycler view item, you need a view from that item on which you want to show it. 
`mRecyclerView.addOnScrollListener(new RecyclerPauseOnScrollListener(WooplrImageLoader.getInstance(),
                UILOptions.pauseOnScroll, UILOptions.pauseOnFling, new RecyclerView.OnScrollListener() {
@Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
            }

@Override
            public void onScrollStateChanged(final RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
if (newState == RecyclerView.SCROLL_STATE_IDLE) {
/**Now you need an item position to retrieve view. You can use first or last completely visible item position methods from recycler view class to get required position which must be visible on the screen.*/

RecyclerView.ViewHolder view = recyclerView.findViewHolderForAdapterPosition(pos);
if (view != null) {
                                    View icon = view.itemView.findViewById(R.id.imgIcon);
//Now show spotlight on this view.
spotlight = spotlightBuilder.target(icon).show();
}
}
}
}));`

**Comment by dhavalwooplr** [comment]
@hardikamal To show a spotlight in the recycler view item, you need a view from that item on which you want to show it. 

Following is the code snippet to show it in the recycler view item.

mRecyclerView.addOnScrollListener(new RecyclerPauseOnScrollListener(ImageLoader.getInstance(),
                UILOptions.pauseOnScroll, UILOptions.pauseOnFling, new RecyclerView.OnScrollListener() {
            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
            }

           @Override
            public void onScrollStateChanged(final RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);

               if (newState == RecyclerView.SCROLL_STATE_IDLE) {
                   
                  //Now you need an item position to retrieve view. You can use first or last completely visible
                 //item position methods from recycler view class to get required position which must be
                //visible on the screen.

                RecyclerView.ViewHolder view = recyclerView.findViewHolderForAdapterPosition(pos);
                if (view != null) {
                       View icon = view.itemView.findViewById(R.id.imgIcon);
                      
                       //Now show spotlight on this view.
                      spotlight = spotlightBuilder.target(icon).show();
                }
            }
        }
}));

**Comment by rameshvoltella** [comment]
@hardikamal how you want to show like on item click of recyclerview or the any sub-view click on a the item
