### ISSUE TITLE
set targetView as Toolbar menu item?

### ISSUE THREAD

**Issue by amarilindra** [wooplr/Spotlight#35]
Hai, I have some items in toolbar menu and I need to use it as view. I tried findViewById(int) but it's not working. 

Any solution ?
Thanks

**Comment by jml90** [comment]
Take a look at this post:

http://stackoverflow.com/questions/8614293/android-get-view-reference-to-a-menu-item

**Comment by amiguels** [comment]
I have successfully implemented `Spotlight` on a `Toolbar` menu item using the method described in the second answer from [this post ](http://stackoverflow.com/questions/10397613/how-can-i-get-the-current-location-of-an-actionbar-menuitem)(using `ViewTreeObserver`).
