### ISSUE TITLE
Exception in Pre-lollipop using Eclipse 

### ISSUE THREAD

**Issue by themhsami** [wooplr/Spotlight#38]
Using this Plugin with **eclipse** causing exception on **pre-lollipop** .
I studied a lot about this and finally comes to know the exception is occuring due to VectorDrawableSupport library.
**Solution** of this problem for **Android studio** is very simple to add this in app/build.gradle :
android {  
   defaultConfig {  
     vectorDrawables.useSupportLibrary = true  
    }  
 }

but i am unable to solve this problem in eclipse this problem is forcing me to not use this awesome library. 
Can you solve my problem for eclipse.

Here is logcat

- 1. E/VdcInflateDelegate(31205): org.xmlpull.v1.XmlPullParserException: Binary XML file line #2<vector> tag requires viewportWidth > 0
- 2. 11-30 15:37:57.908: E/VdcInflateDelegate(31205): 	at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:535)
- 3. 11-30 15:37:57.908: E/VdcInflateDelegate(31205): 	at android.support.graphics.drawable.VectorDrawableCompat.updateStateFromTypedArray(VectorDrawableCompat.java:535)
- 4. 11-30 15:37:57.908: E/VdcInflateDelegate(31205): 	at android.support.graphics.drawable.VectorDrawableCompat.inflate(VectorDrawableCompat.java:472)
- 5. 11-30 15:37:57.908: E/VdcInflateDelegate(31205): 	at android.support.graphics.drawable.VectorDrawableCompat.createFromXmlInner(VectorDrawableCompat.java:436)
- 6. 11-30 15:37:57.908: E/VdcInflateDelegate(31205): 	at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:851)
- 7. 11-30 15:37:57.908: E/VdcInflateDelegate(31205): 	at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:320)
- 8. 11-30 15:37:57.908: E/VdcInflateDelegate(31205): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
- 9. 11-30 15:37:57.908: E/VdcInflateDelegate(31205): 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
- 10. 11-30 15:37:57.908: E/VdcInflateDelegate(31205): 	at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:66)
- 11. 11-30 15:37:57.908: E/VdcInflateDelegate(31205): 	at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:71)
- 12. 11-30 15:37:57.908: E/VdcInflateDelegate(31205): 	at **com.wooplr.spotlight.SpotlightView.addArcAnimation(SpotlightView.java:489)**
- 13. 11-30 15:37:57.908: E/VdcInflateDelegate(31205): 	at com.wooplr.spotlight.SpotlightView.access$10(SpotlightView.java:487)
- 14. 11-30 15:37:57.908: E/VdcInflateDelegate(31205): 	at com.wooplr.spotlight.SpotlightView$4.onAnimationEnd(SpotlightView.java:442)
- 15.

**Comment by 29jitender** [comment]
@themhsami you should use gradle plugin to support this on Eclipse. 
https://gradle.org/eclipse/
