### ISSUE TITLE
How to perform onClick

### ISSUE THREAD

**Issue by sahuam1** [wooplr/Spotlight#39]
I want to make target view invisible on performing onclick or please suggest any other option to do the same.

**Comment by dhavalwooplr** [comment]
Following are few methods you can use for that:

`performClick(boolean)` - Perform a click on target view
`dismissOnTouch(boolean)` - Dismiss spotlight on touch outside
`enableDismissAfterShown(boolean)` - Dismiss spotlight on touch outside after spotlight is completely visible

If this is not you want then please elaborate more.
