### ISSUE TITLE
Dismiss/hide Spotlight

### ISSUE THREAD

**Issue by amiguels** [wooplr/Spotlight#41]
Hello! First off, I'd like to thank you for this amazing library.

My app handles orientation changes on it's own, without running onCreate again. When this happens the spotlight becomes misaligned. Therefore, I'd like to be able to dismiss the currently showing spotlight so I can draw a new one using the new orientation.
I haven't been able to find a method to dismiss the spotlight, is there one available?

Thanks!

**Comment by amiguels** [comment]
I have looked into the code of SpotlightView and found out two methods of interest - `private void dismiss()` and `private void removeSpotlightView()`. I have set them to `public` used them without trouble.

**Comment by dhavalwooplr** [comment]
You can use this newly added version or `removeSpotlightView()` to dismiss spotlight when orientation changes.

`public void removeSpotlightView(boolean needOnUserClickedCallback)`

```
@Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);

        if(spotLight.isShown()){
            spotLight.removeSpotlightView(false);//Remove current spotlight view from parent
            showSpotlight();//Show it again in new orientation if required.
        }
    }
```
