### ISSUE TITLE
Handling orientation changes

### ISSUE THREAD

**Issue by amiguels** [wooplr/Spotlight#43]
When the SpotlightView is showing and the app is set to handle orientation changes on its own (without re-running `onCreate`), the SpotlightView becomes misaligned.

**Comment by amiguels** [comment]
I have fixed this by applying the modification mentioned [here](https://github.com/wooplr/Spotlight/issues/42) and then using the following code:

```
  @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);

        if(spotlight.isShown()){
            spotlight.removeSpotlightView();
            showSpotlight();
        }
    }
```

**Comment by dhavalwooplr** [comment]
You can use this newly added version or `removeSpotlightView()` when orientation changes.

`public void removeSpotlightView(boolean needOnUserClickedCallback)`

```
@Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);

        if(spotLight.isShown()){
            spotLight.removeSpotlightView(false);//Remove current spotlight view from parent
            showSpotlight();//Show it again in new orientation if required.
        }
    }
```
