### ISSUE TITLE
Landscape causes some text to be hidden

### ISSUE THREAD

**Issue by rakanalh** [wooplr/Spotlight#44]
Hello,

When using the app in landscape orientation, android's virtual buttons hide some parts of the text when the tutorial is displayed. This area was probably not taken into account?

![Example](http://i.imgur.com/kIsYpK8.png)

**Comment by 29jitender** [comment]
Thanks for reporting @rakanalh. I will check this one ASAP

**Comment by dhavalwooplr** [comment]
It is fixed now. you will be able to find it in new release.
