### ISSUE TITLE
Can't find SpotlightSequence class in com.wooplr.spotlight.utils package

### ISSUE THREAD

**Issue by mohanishn1234** [wooplr/Spotlight#46]
nice work dude.. appreciated. But one thing I could found  in your lib is ' SpotlightSequence ' in '
 ' com.wooplr.spotlight.utils ' package. But when imported from gradle couldn't found the same. Could you help me in this ?

**Comment by dhavalwooplr** [comment]
Thanks. You can find it in the new release `com.github.wooplr:Spotlight:1.2.3`
