### ISSUE TITLE
Add showcase on navigation drawer menu items

### ISSUE THREAD

**Issue by sajjadG** [wooplr/Spotlight#47]
Hi
navigation drawer items are not views. how can we add showcase for them?

**Comment by dhavalwooplr** [comment]
Can you please share a screenshot where exactly you want to show it in the navigation drawer?

**Comment by sajjadG** [comment]
![image](https://cloud.githubusercontent.com/assets/380602/23097131/c6f1631e-f641-11e6-9875-8bff6394fce3.png)

I want to open showcase on navigation drawer menu item and it's not a View. it's a MenuItem so I'm using PointTarget for now but I think there should be better way to do that.
This is the code I'm using:
```
Button closeButton = new Button(this);
        closeButton.setBackgroundColor(200);
        closeButton.setEnabled(false);

        showcaseView = new ShowcaseView.Builder(this)
                .setTarget(new PointTarget(330, 570))
//                .setTarget(new ViewTarget(((Toolbar) findViewById(R.id.toolbar)).getChildAt(0)))//works
                .setContentTitle("Add a new device")
                .setContentText("You need to add a new device to be able to use this app")
//                .hideOnTouchOutside()
                .setStyle(R.style.CustomShowcaseTheme2)
                .replaceEndButton(closeButton)
                .build();
```

**Comment by dhavalwooplr** [comment]
Please check #35 , You can get a view from menu item, refer to the given links.
