### ISSUE TITLE
maskcolor is not transparent.

### ISSUE THREAD

**Issue by Ankur008** [wooplr/Spotlight#48]
thanks for this awesome library. But I am not able to set the mask color to transparent. How do i do?
 
            config.setIntroAnimationDuration(400);
            config.setFadingTextDuration(400);
            config.setHeadingTvSize(32);
            config.setSubHeadingTvSize(16);
            config.setMaskColor(android.R.color.transparent);
            config.setLineAnimationDuration(400);
            config.setDismissOnTouch(true);
            config.setDismissOnBackpress(true);
            config.setRevealAnimationEnabled(true);
            config.setPerformClick(true);

but still getting the primary color background. any idea?

**Comment by dhavalwooplr** [comment]
Following are the effects of using different Mask color. Is this what you want?

1. config.maskColor(Color.parseColor("#dc000000"))
![device-2017-02-17-122202](https://cloud.githubusercontent.com/assets/12393690/23055542/6e698a22-f50c-11e6-8f57-45995ceba818.png)

2. config.setMaskColor(android.R.color.transparent)
![device-2017-02-17-122409](https://cloud.githubusercontent.com/assets/12393690/23055590/ac61f68e-f50c-11e6-8498-3f4353cd63ab.png)
