### ISSUE TITLE
Resources Not Found

### ISSUE THREAD

**Issue by ParhamAhmadi** [wooplr/Spotlight#5]
android.content.res.Resources$NotFoundException: File res/drawable/ic_spotlight_arc.xml from drawable resource ID #0x7f0200b0

	new SpotlightView.Builder(this).introAnimationDuration(this.introAnimationDuration)
				.enableRevalAnimation(this.isFadeAnimationEnabled).performClick(this.isPerformClick)
				.fadeinTextDuration(this.fadingTextDuration).setTypeface(this.typeface)
				.headingTvColor(this.headingTvColor).headingTvSize(this.headingTvSize).headingTvText(this.headingTvText)
				.subHeadingTvColor(this.subHeadingTvColor).subHeadingTvSize(this.subHeadingTvSize)
				.subHeadingTvText(this.subHeadingTvText).maskColor(this.maskColor).target(this.view)
				.lineAnimDuration(this.lineAnimDuration).lineAndArcColor(this.lineAndArcColor)
				.dismissOnTouch(this.dismissOnTouch).enableDismissAfterShown(this.enableDismissAfterShown)
				.usageId(this.usageId) // UNIQUE
				// ID
				.show();

@

**Comment by Mudlt** [comment]
It's same as issue #1 try version 1.1. It works.
