### ISSUE TITLE
reset usage id

### ISSUE THREAD

**Issue by TheLoyalCruel** [wooplr/Spotlight#52]
Hi thanks for the beautiful lib
is there any method to reset all and show again spotlight?

thanks in advance...

**Comment by dhavalwooplr** [comment]
Hi @TheLoyalCruel, Thanks.

You can use `resetAllUsageIds(), resetUsageId(String id)` methods from SpotlightView class for that. You will be able to use it from our next release "1.2.4"

**Comment by Debdeep009** [comment]
Create an instance of `PreferencesManager` (present inside Spotlight) and use the method `resetAll()`

**Comment by Urvika-gola** [comment]
@Debdeep009  Can you provide the code for that?
