### ISSUE TITLE
Clear Usage IDs

### ISSUE THREAD

**Issue by JoelBryceAnderson** [wooplr/Spotlight#9]
There ought to be a way to clear SharedPreferences so the spotlights can show up again. Is this possible at all?

**Comment by JoelBryceAnderson** [comment]
Never mind, figured it out using the same internal ResetAll method.

**Comment by TheLoyalCruel** [comment]
@JoelBryceAnderson 
Hi is there anyway to reset spotlight?

**Comment by JoelBryceAnderson** [comment]
Yes. See here. https://github.com/wooplr/Spotlight/blob/master/Spotlight-library/src/main/java/com/wooplr/spotlight/prefs/PreferencesManager.java
